---
name: "pre-release"

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: "build binary"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: set up go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: build
        run: sh build.sh

  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: "Build & test"
        run: |
          pwd
          ls -l
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE
            mdns-proxy