name: Publish Release YAML

on:
  release:
    types:
      - 'created'

jobs:
  publish-release-yaml:
    name: Publish Release YAML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - uses: actions/checkout@v3
      - uses: ko-build/setup-ko@v0.6

      - name: Generate and upload release.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag=${GITHUB_REF#refs/*/}
          ko resolve -f config/kubernetes.yaml -B --platform=linux/arm64,linux/amd64 -t ${tag} > k8s.yaml
          gh release upload ${tag} k8s.yaml

